/* <![CDATA[ */
var wpData = {
    "degrees": [{
          "ID": 443,
          "post_author": "1",
          "post_date": "2017-06-14 20:52:12",
          "post_date_gmt": "2017-06-14 20:52:12",
          "post_content": "",
          "post_title": "B.A.\/B.S. Integrated Marketing Communications",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "ba-bs-bachelors-integrated-marketing-communications",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2018-03-13 18:29:49",
          "post_modified_gmt": "2018-03-13 18:29:49",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "http:\/\/uwa-gulp.dev\/?post_type=degrees&#038;p=443",
          "menu_order": 0,
          "post_type": "degrees",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw",
          "degree_areas": [{
            "term_id": 34,
            "name": "Communications",
            "slug": "communications",
            "term_group": 0,
            "term_taxonomy_id": 34,
            "taxonomy": "degree_vertical",
            "description": "",
            "parent": 0,
            "count": 1,
            "filter": "raw"
          }],
          "degree_levels": [{
            "term_id": 4,
            "name": "Bachelor's Degrees",
            "slug": "bachelors",
            "term_group": 0,
            "term_taxonomy_id": 4,
            "taxonomy": "degree_level",
            "description": "",
            "parent": 0,
            "count": 9,
            "filter": "raw"
          }]
        }, {
          "ID": 449,
          "post_author": "1",
          "post_date": "2017-06-14 21:28:57",
          "post_date_gmt": "2017-06-14 21:28:57",
          "post_content": "",
          "post_title": "B.A.\/B.S. Interdisciplinary Studies",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "ba-bs-bachelors-interdisciplinary-studies",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2018-03-13 18:25:17",
          "post_modified_gmt": "2018-03-13 18:25:17",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "http:\/\/uwa-gulp.dev\/?post_type=degrees&#038;p=449",
          "menu_order": 0,
          "post_type": "degrees",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw",
          "degree_areas": [{
            "term_id": 33,
            "name": "General Studies",
            "slug": "general-studies",
            "term_group": 0,
            "term_taxonomy_id": 33,
            "taxonomy": "degree_vertical",
            "description": "",
            "parent": 0,
            "count": 2,
            "filter": "raw"
          }],
          "degree_levels": [{
            "term_id": 4,
            "name": "Bachelor's Degrees",
            "slug": "bachelors",
            "term_group": 0,
            "term_taxonomy_id": 4,
            "taxonomy": "degree_level",
            "description": "",
            "parent": 0,
            "count": 9,
            "filter": "raw"
          }]
        }, {
          "ID": 338,
          "post_author": "1",
          "post_date": "2017-05-18 20:01:00",
          "post_date_gmt": "2017-05-18 20:01:00",
          "post_content": "",
          "post_title": "B.A.\/B.S. Psychology",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "ba-bs-bachelors-psychology",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2018-03-13 18:42:25",
          "post_modified_gmt": "2018-03-13 18:42:25",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "http:\/\/uwa.loc\/?post_type=degrees&#038;p=338",
          "menu_order": 0,
          "post_type": "degrees",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw",
          "degree_areas": [{
            "term_id": 8,
            "name": "Psychology &amp; Counseling",
            "slug": "psychology-counseling",
            "term_group": 0,
            "term_taxonomy_id": 8,
            "taxonomy": "degree_vertical",
            "description": "",
            "parent": 0,
            "count": 6,
            "filter": "raw"
          }],
          "degree_levels": [{
            "term_id": 4,
            "name": "Bachelor's Degrees",
            "slug": "bachelors",
            "term_group": 0,
            "term_taxonomy_id": 4,
            "taxonomy": "degree_level",
            "description": "",
            "parent": 0,
            "count": 9,
            "filter": "raw"
          }]
        }, {
          "ID": 225,
          "post_author": "1",
          "post_date": "2017-04-22 22:58:54",
          "post_date_gmt": "2017-04-22 22:58:54",
          "post_content": "",
          "post_title": "B.S. Business Administration",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "bba-bachelor-business-administration",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2018-03-13 18:53:32",
          "post_modified_gmt": "2018-03-13 18:53:32",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "http:\/\/uwa.loc\/?post_type=degrees&#038;p=225",
          "menu_order": 0,
          "post_type": "degrees",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw",
          "degree_areas": [{
            "term_id": 6,
            "name": "Business",
            "slug": "business",
            "term_group": 0,
            "term_taxonomy_id": 6,
            "taxonomy": "degree_vertical",
            "description": "",
            "parent": 0,
            "count": 2,
            "filter": "raw"
          }],
          "degree_levels": [{
            "term_id": 4,
            "name": "Bachelor's Degrees",
            "slug": "bachelors",
            "term_group": 0,
            "term_taxonomy_id": 4,
            "taxonomy": "degree_level",
            "description": "",
            "parent": 0,
            "count": 9,
            "filter": "raw"
          }]
        }, {
          "ID": 367,
          "post_author": "1",
          "post_date": "2017-06-08 20:37:48",
          "post_date_gmt": "2017-06-08 20:37:48",
          "post_content": "",
          "post_title": "B.S. Early Childhood Development",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "bs-bachelors-early-childhood-development",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2018-03-13 18:40:45",
          "post_modified_gmt": "2018-03-13 18:40:45",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "http:\/\/uwa.loc\/?post_type=degrees&#038;p=367",
          "menu_order": 0,
          "post_type": "degrees",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw",
          "degree_areas": [{
            "term_id": 32,
            "name": "Early Childhood",
            "slug": "early-childhood",
            "term_group": 0,
            "term_taxonomy_id": 32,
            "taxonomy": "degree_vertical",
            "description": "",
            "parent": 7,
            "count": 6,
            "filter": "raw"
          }, {
            "term_id": 7,
            "name": "Teaching",
            "slug": "teaching",
            "term_group": 0,
            "term_taxonomy_id": 7,
            "taxonomy": "degree_vertical",
            "description": "",
            "parent": 0,
            "count": 40,
            "filter": "raw"
          }],
          "degree_levels": [{
            "term_id": 4,
            "name": "Bachelor's Degrees",
            "slug": "bachelors",
            "term_group": 0,
            "term_taxonomy_id": 4,
            "taxonomy": "degree_level",
            "description": "",
            "parent": 0,
            "count": 9,
            "filter": "raw"
          }]
        }, {
          "ID": 475,
          "post_author": "1",
          "post_date": "2017-06-22 17:47:32",
          "post_date_gmt": "2017-06-22 17:47:32",
          "post_content": "",
          "post_title": "B.S. Elementary Education, K-6\/P-3",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "bs-bachelors-elementary-education-k-6-includes-certification-in-early-childhood-p-3",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2018-03-13 17:41:38",
          "post_modified_gmt": "2018-03-13 17:41:38",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "http:\/\/uwa-gulp.dev\/?post_type=degrees&#038;p=475",
          "menu_order": 0,
          "post_type": "degrees",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw",
          "degree_areas": [{
            "term_id": 27,
            "name": "Elementary Education",
            "slug": "elementary-education",
            "term_group": 0,
            "term_taxonomy_id": 27,
            "taxonomy": "degree_vertical",
            "description": "",
            "parent": 7,
            "count": 5,
            "filter": "raw"
          }, {
            "term_id": 7,
            "name": "Teaching",
            "slug": "teaching",
            "term_group": 0,
            "term_taxonomy_id": 7,
            "taxonomy": "degree_vertical",
            "description": "",
            "parent": 0,
            "count": 40,
            "filter": "raw"
          }],
          "degree_levels": [{
            "term_id": 4,
            "name": "Bachelor's Degrees",
            "slug": "bachelors",
            "term_group": 0,
            "term_taxonomy_id": 4,
            "taxonomy": "degree_level",
            "description": "",
            "parent": 0,
            "count": 9,
            "filter": "raw"
          }, {
            "term_id": 13,
            "name": "Teaching Certificates",
            "slug": "teaching-certificates",
            "term_group": 0,
            "term_taxonomy_id": 13,
            "taxonomy": "degree_level",
            "description": "",
            "parent": 0,
            "count": 33,
            "filter": "raw"
          }]
        }, {
          "ID": 581,
          "post_author": "1",
          "post_date": "2017-07-19 18:29:06",
          "post_date_gmt": "2017-07-19 18:29:06",
          "post_content": "",
          "post_title": "B.S. Public Safety",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "bs-bachelors-public-safety",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2018-03-13 16:52:51",
          "post_modified_gmt": "2018-03-13 16:52:51",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "http:\/\/uwa-gulp.dev\/?post_type=degrees&#038;p=581",
          "menu_order": 0,
          "post_type": "degrees",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw",
          "degree_areas": [{
            "term_id": 24,
            "name": "Public Safety",
            "slug": "public-safety",
            "term_group": 0,
            "term_taxonomy_id": 24,
            "taxonomy": "degree_vertical",
            "description": "",
            "parent": 0,
            "count": 1,
            "filter": "raw"
          }],
          "degree_levels": [{
            "term_id": 4,
            "name": "Bachelor's Degrees",
            "slug": "bachelors",
            "term_group": 0,
            "term_taxonomy_id": 4,
            "taxonomy": "degree_level",
            "description": "",
            "parent": 0,
            "count": 9,
            "filter": "raw"
          }]
        }, {
          "ID": 476,
          "post_author": "1",
          "post_date": "2017-06-22 17:59:33",
          "post_date_gmt": "2017-06-22 17:59:33",
          "post_content": "",
          "post_title": "B.S. Special Education: Collaborative Teacher, K-6\/6-12",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "bs-bachelors-collaborative-teacher-special-education-k-12",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2018-03-13 17:37:06",
          "post_modified_gmt": "2018-03-13 17:37:06",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "http:\/\/uwa-gulp.dev\/?post_type=degrees&#038;p=476",
          "menu_order": 0,
          "post_type": "degrees",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw",
          "degree_areas": [{
            "term_id": 31,
            "name": "Special Education",
            "slug": "special-education",
            "term_group": 0,
            "term_taxonomy_id": 31,
            "taxonomy": "degree_vertical",
            "description": "",
            "parent": 7,
            "count": 7,
            "filter": "raw"
          }, {
            "term_id": 7,
            "name": "Teaching",
            "slug": "teaching",
            "term_group": 0,
            "term_taxonomy_id": 7,
            "taxonomy": "degree_vertical",
            "description": "",
            "parent": 0,
            "count": 40,
            "filter": "raw"
          }],
          "degree_levels": [{
            "term_id": 4,
            "name": "Bachelor's Degrees",
            "slug": "bachelors",
            "term_group": 0,
            "term_taxonomy_id": 4,
            "taxonomy": "degree_level",
            "description": "",
            "parent": 0,
            "count": 9,
            "filter": "raw"
          }, {
            "term_id": 13,
            "name": "Teaching Certificates",
            "slug": "teaching-certificates",
            "term_group": 0,
            "term_taxonomy_id": 13,
            "taxonomy": "degree_level",
            "description": "",
            "parent": 0,
            "count": 33,
            "filter": "raw"
          }]
        }, {
          "ID": 290,
          "post_author": "1",
          "post_date": "2017-04-28 19:06:39",
          "post_date_gmt": "2017-04-28 19:06:39",
          "post_content": "",
          "post_title": "B.S. Technology",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "btech-bachelors-technology",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2018-03-13 18:45:50",
          "post_modified_gmt": "2018-03-13 18:45:50",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "http:\/\/uwa.loc\/?post_type=degrees&#038;p=290",
          "menu_order": 0,
          "post_type": "degrees",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw",
          "degree_areas": [{
                "term_id": 33,
                "name": "General Studies",
                "slug": "general-studies",
                "term_group": 0,
                "term_taxonomy_id": 33,
                "taxonomy": "degree_vertical",
                "description": "",
                "parent": 0,
                "count": 2,
                "…
